package sustainico_backend.Models;
import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import lombok.*;

import java.time.Instant;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Getter
@Setter
@DynamoDBTable(tableName = "user")
public class User {

    @DynamoDBAutoGeneratedKey
    @DynamoDBHashKey(attributeName = "userId")
    private String userId;

    @DynamoDBAttribute(attributeName = "userName")
    private String userName;

    @DynamoDBIndexHashKey(globalSecondaryIndexName = "contactNoIndex", attributeName = "contactNo")
    @NonNull
    private String contactNo;

    @DynamoDBAttribute(attributeName = "address")
    private String address;

    @DynamoDBAttribute(attributeName = "email")
    private String email;

    @DynamoDBAttribute(attributeName = "newUser")
    private Boolean newUser;

    @DynamoDBAttribute(attributeName = "timestamp")
    private String timestamp = String.valueOf(Instant.now().getEpochSecond());
}
